version: '3.2'
services:
  web-client:
    restart: always
    stdin_open: true
    tty: true
    image: beamylabs/beamybroker-web-client:${BEAMYWEBCLIENT_TAG:-latest}
    environment:
      SIGNAL_SERVER_HOST_NAME: ${SIGNALBROKER_IP}
    ports:
     - "8080:8080"
    depends_on:
     - proxy
  proxy:
    restart: always
    image: beamylabs/grpcwebproxy:${GRPCWEBPROXY_TAG:-latest}
    ports:
      - "8081:8080"
    command: ./grpcwebproxy --backend_addr=${SIGNALBROKER_IP:?Add SIGNALBROKER_IP to the .env file}:50051 --run_tls_server=false --allow_all_origins --server_http_max_read_timeout 0s --server_http_max_write_timeout 0s
