version: '3.2'
services:

  web-client:
    restart: always
    stdin_open: true
    tty: true
    image: beamylabs/beamybroker-web-client:${BEAMYWEBCLIENT_TAG:-latest}
    volumes:
      - "${CONFIG_FOLDER:-./configuration}:/service_client/configuration"
    ports:
      - "8080:8080"

  signal-broker:
    tty: true
    restart: always
    image: beamylabs/beamybroker-server:${BEAMYBROKER_TAG:-latest}
    network_mode: "host"
    # Mount the folder "configuration" folder into container. Itself
    # configurable through an environment variable (or set in a .env file).
    volumes:
      - "${CONFIG_FOLDER:-./configuration}:/signalbroker/_build/prod/rel/signal_server/configuration"
    # Use this if you need to customize the command that this container runs;
    # set the variable in a .env file.
    # command: "${CUSTOM_COMMAND}"
    environment:
      - REPLACE_OS_VARS=true
      - COOKIE=test
      - NODENAME=node@${NODE_NAME:-unset.example.com}
